### ISSUE TITLE
Move Tree Validator fails to correctly parse alternative lines

### ISSUE THREAD

**Issue by YuraVolk** [YuraVolk/chess-variants-wiki#35]
MoveTreeValidator.ts while parsing alternative lines commonly fails to obtain the correct selected move, may be an issue with MoveTree.getMove with wrong alternative line paths. When the move paths are incorrect, it fails loudly, otherwise fails quietly and quits.

`console.error
    Trace: Error: The selected move is not a valid move
        at assertValidMove (E:\4pc-wiki\src\main\client\ts\logic\movegen\MoveTree\MoveTree.ts:64:9)
        at traverse (E:\4pc-wiki\src\main\client\ts\logic\movegen\MoveTree\MoveTreeValidator.ts:99:19)
        at traverse (E:\4pc-wiki\src\main\client\ts\logic\movegen\MoveTree\MoveTreeValidator.ts:90:42)
        at validateMoveTree (E:\4pc-wiki\src\main\client\ts\logic\movegen\MoveTree\MoveTreeValidator.ts:108:2)
        at InsufficientMaterialConstructor.callback (E:\4pc-wiki\src\main\client\ts\logic\index\GameBoardWorker.ts:108:39)
        at InsufficientMaterialConstructor.generateInsufficientMaterialState (E:\4pc-wiki\src\main\client\ts\logic\movegen\VariantRules\VariantRuleDefinitions\BoardVariantModules\InsufficientMaterial\InsufficientMaterialConstructor.ts:383:25)`

- [x] Fix PGN move parsing errors and path mismatch
- [x] Fix MoveTreeValidator keeping empty lines
- [x] MoveTreeValidator not parsing alternative line strings
- [x] Multiple alternative lines not being parsed
- [x] Depth 3 alternative lines not being parsed

**Comment by YuraVolk** [comment]
Fixed in https://github.com/YuraVolk/chess-variants-wiki/commit/e481b01814c57ae38bcbbc384f300fae42d50409.
